[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["npm --prefix backend install", "pip install 'yt-dlp[default]' curl-cffi"]

[phases.build]
cmds = ["npm --prefix backend run build"]

[start]
cmd = "npm --prefix backend start"
