[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python311Packages.pip", "ffmpeg", "yt-dlp"]

[phases.install]
cmds = ["npm install", "pip install yt-dlp curl-cffi"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
